/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisAnalysisIdRouteImport } from './routes/analysis/$analysisId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisAnalysisIdRoute = AnalysisAnalysisIdRouteImport.update({
  id: '/analysis/$analysisId',
  path: '/analysis/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis/$analysisId': typeof AnalysisAnalysisIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis/$analysisId': typeof AnalysisAnalysisIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis/$analysisId': typeof AnalysisAnalysisIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analysis/$analysisId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analysis/$analysisId'
  id: '__root__' | '/' | '/analysis/$analysisId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisAnalysisIdRoute: typeof AnalysisAnalysisIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$analysisId': {
      id: '/analysis/$analysisId'
      path: '/analysis/$analysisId'
      fullPath: '/analysis/$analysisId'
      preLoaderRoute: typeof AnalysisAnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisAnalysisIdRoute: AnalysisAnalysisIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
